#!/usr/bin/env python3
"""Assemble the living paper and log; rebuild its LaTeX/PDF by default.

--markdown-only updates generated text without compiling a PDF.
--check checks generated text freshness and registry/certificate consistency.
The current result is explicitly selected in results/registry.json.
"""
import argparse
import re
from datetime import date
from fractions import Fraction as Q
import shutil
import subprocess

from result_registry import ROOT, load, exact_decimal

BUILD = ROOT / 'tex/build'
TITLE = 'Finite Network Improvements for the Exact Discrete Fourier Transform'


def result_table(entries):
    rows = ['| Date | Result | Status | Fourier saving $\\delta$ | Tensor witness $a$ |',
            '| --- | --- | --- | ---: | ---: |']
    for r in entries:
        delta = exact_decimal(r['fourier_saving']) if r.get('fourier_saving') else 'pending'
        a = exact_decimal(r['tensor_saving']) if r.get('tensor_saving') else 'see record'
        rows.append(f'| {r["date"]} | [{r["name"]}]({r["record"]}) | {r["status"]} | `{delta}` | `{a}` |')
    return '\n'.join(rows)


def generated(registry, current):
    delta = exact_decimal(current['fourier_saving'])
    a = exact_decimal(current['tensor_saving'])
    updated = current['date']
    intro = f'''# {TITLE}

**Living research draft. Selected result: {current['id']}, {updated}.**

<!-- Generated by scripts/build_manuscript.py from paper/framework.md and the selected result record. -->

We give a reusable conditional transfer from finite complex tensor networks to the exact discrete Fourier transform, together with versioned network witnesses. The current proposed all-length bound is

\\[
\\boxed{{T(n)=O\\!\\left(n(\\log n)^{{1-\\delta}}\\right),\\qquad
\\delta={delta}.}}
\\]

The selected finite witness has strict tensor saving $a={a}$. Independent mathematical review and end-to-end formal verification remain pending. This paper separates the reusable transfer theorem, the selected construction, and the history of incorporated improvements. No practical FFT speedup is claimed.

'''
    records = current.get('paper_records', [current['record']])
    manuscript = intro + (ROOT/'paper/framework.md').read_text().rstrip() + '\n\n'
    manuscript += '\n\n'.join((ROOT/path).read_text().rstrip() for path in records) + '\n'
    # The publication carries a compact history as well as the standalone log.
    history = '\n## Incorporated result history\n\n'
    history += 'These are project records, not priority claims. All remain proposed transfers. Ratios compare exponent savings, not runtimes.\n\n'
    history += '| Date | Witness | Fourier saving |\n| --- | --- | ---: |\n'
    for r in registry['results']:
        if r['status'] != 'candidate':
            history += f'| {r["date"]} | {r["id"]} | `{exact_decimal(r["fourier_saving"])}` |\n'
    history += '\nThe full log, record links and update workflow are in `IMPROVEMENTS.md` and `results/README.md`. Earlier assembled papers remain under `archive/`.\n'
    manuscript += history
    log = '''# Improvement log

Generated from [results/registry.json](results/registry.json). Dates identify project records, not priority claims. `proposed` means a written conditional transfer with finite checks; it does not mean independent review or formal verification. Candidate values never replace the current result automatically.

'''
    log += f'Current selection: **[{current["name"]}]({current["record"]})**, with proposed `delta={delta}`.\n\n'
    log += result_table(registry['results']) + '\n\n'
    previous = None
    for r in registry['results']:
        log += f'## {r["date"]}: {r["name"]}\n\n{r["change"]}\n\n'
        log += f'[Result record]({r["record"]})'
        if r['status'] != 'candidate':
            log += f' · [Reference certificate]({r["certificate"]}) · [Verifier]({r["verifier"]})'
            d = Q(r['fourier_saving'])
            if previous:
                log += f'\n\nThe Fourier exponent saving is approximately **{float(d/previous):,.2f} times** the preceding incorporated result. This compares exponent parameters, not running times.'
            previous = d
        log += '\n\n'
    log += 'The original OpenAI #130 published headline is `delta=1e-13`. The older short proof also retains the `5.2e-10` and `5.3e-10` fallbacks. See [the update workflow](results/README.md) before adding or promoting a result.\n'
    summary = f'''Current selection: **[{current['name']}]({current['record']})**, recorded {updated}.

```math
T(n)=O\\left(n(\\log n)^{{1-\\delta}}\\right),\\qquad \\delta={delta}.
```

The exact tensor witness is `a={a}` and the chosen Fourier saving is `delta={delta}`. This is a **proposed conditional transfer**, supported by a written argument and finite checks. Independent mathematical review and end-to-end formal verification remain pending.'''
    readme = (ROOT/'README.md').read_text()
    start, end = '<!-- current-result:start -->', '<!-- current-result:end -->'
    if start not in readme or end not in readme:
        raise ValueError('README is missing the generated result markers')
    before, rest = readme.split(start, 1)
    _, after = rest.split(end, 1)
    readme = before + start + '\n\n' + summary + '\n\n' + end + after
    return {'manuscript.md': manuscript, 'IMPROVEMENTS.md': log, 'README.md': readme}


def run(command, log):
    result = subprocess.run(command, cwd=ROOT, text=True, stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT, check=False)
    (BUILD / log).write_text(result.stdout)
    if result.returncode:
        raise SystemExit(f'{command[0]} failed:\n{result.stdout[-6000:]}')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--markdown-only', action='store_true')
    args = parser.parse_args()
    registry, current = load()
    outputs = generated(registry, current)
    if args.check:
        stale = [name for name, text in outputs.items()
                 if not (ROOT/name).exists() or (ROOT/name).read_text() != text]
        if stale:
            raise SystemExit('Generated text is stale: '+', '.join(stale))
        print('Result registry, reference parameters, and generated text agree.')
        return
    for name, text in outputs.items():
        (ROOT/name).write_text(text)
    if args.markdown_only:
        print('Updated manuscript.md, IMPROVEMENTS.md and README result summary.')
        return
    BUILD.mkdir(exist_ok=True)
    body = outputs['manuscript.md'].split('\n', 2)[2]
    body = '\n'.join(line for line in body.splitlines()
                     if not line.startswith('**Living research draft.') and not line.startswith('<!--'))
    body = body.replace('\n| $r$ |', '\n\\Needspace{19\\baselineskip}\n\n| $r$ |')
    # Keep a table-only subsection's heading and lead-in with its table.
    body = re.sub(r'(### [^\n]+\n\n[^\n]+\n\n)\\Needspace\{19\\baselineskip\}\n\n',
                  lambda match: '\\Needspace{23\\baselineskip}\n\n'+match.group(1), body)
    input_path = BUILD / 'body.md'
    input_path.write_text(body)
    label_date = date.fromisoformat(current['date']).strftime('%B %d, %Y').replace(' 0', ' ')
    run(['pandoc', str(input_path), '--standalone', '--from=markdown+tex_math_single_backslash',
         '--to=latex', '--shift-heading-level-by=-1', '--output=tex/manuscript.tex', '--include-in-header=tex/preamble.tex',
         '--metadata=title:'+TITLE,
         '--metadata=subtitle:Living research draft; selected witness '+current['id'],
         '--metadata=date:'+label_date, '--variable=fontsize:11pt',
         '--variable=geometry:margin=1in', '--variable=colorlinks:true',
         '--variable=urlcolor:blue', '--variable=linkcolor:blue'], 'pandoc.log')
    # Pandoc protects spaces in inline code. Add legal break points in long
    # source pins and repository paths without changing their printed bytes.
    latex_path = ROOT / 'tex/manuscript.tex'
    def wrap_code(match):
        value = match.group(1)
        if re.fullmatch('[0-9a-f]{40}', value):
            value = r'\allowbreak{}'.join(value[i:i+10] for i in range(0, 40, 10))
        elif '/' in value:
            value = value.replace('/', r'/\allowbreak{}').replace(r'\_', r'\_\allowbreak{}')
        return r'\texttt{' + value + '}'
    latex_path.write_text(re.sub(r'\\texttt\{([^{}]*)\}', wrap_code, latex_path.read_text()))
    for pass_number in (1, 2):
        run(['pdflatex', '-interaction=nonstopmode', '-halt-on-error',
             '-output-directory=tex/build', 'tex/manuscript.tex'], f'latex-pass-{pass_number}.log')
    shutil.copyfile(BUILD / 'manuscript.pdf', ROOT / 'manuscript.pdf')
    print('Rebuilt the living manuscript, LaTeX, PDF, improvement log and README summary.')


if __name__ == '__main__':
    main()
